### PR TITLE
Allow consistency to be set from DynamoSingleVersionStore, DynamoMultipleVersionStore

### PR DESCRIPTION
**Pull request by kenoir**
Allows consistency mode to be set in config, in turn allowing DynamoSingleVersionStore, DynamoMultipleVersionStore to have more easily configured consistency.

Helps with https://github.com/wellcomecollection/platform/issues/4873

### CODE REVIEW

**Comment by kenoir** [comment]
I looked for a way to better test this, but I ended up concluding that this compiles and existing tests pass is sufficient.

**Review by alexwlchan — COMMENTED** [review]
I'm not sure this is right – it's a property of the Store, not the Table.

**Comment by kenoir** [comment]
> I'm not sure this is right – it's a property of the Store, not the Table.

Don't understand? The config is being set on the store?

**Comment by alexwlchan** [comment]
>> I'm not sure this is right – it's a property of the Store, not the Table.
>
> Don't understand? The config is being set on the store?

It looks to me like you're adding a third field to DynamoConfig?

**Comment by kenoir** [comment]
> It looks to me like you're adding a third field to DynamoConfig?

Ah I see - my expectation was that `DynamoConfig` was for the store and not the table - but I think you are saying we should scope it to the table only?

**Review by alexwlchan — APPROVED** [review]
Yup, this is what I was suggesting.

**Pull request merged**
